name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install AWS CDK CLI globally
    - name: Install AWS CDK
      run: sudo npm install -g aws-cdk

    # Run `cdk synth`
    - name: CDK Synth
      working-directory: .
      run: cdk synth

    # Deploy CDK application
    - name: CDK Deploy
      working-directory: .
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: cdk deploy --require-approval never
